config/routes.rb
Rails.application.routes.draw do
  resources :contatos do
    collection do
      match :advanced_search, to: 'contatos#index', via: :post
    end
  end

  root 'contatos#index'

end

app/models/contato.rb
class Contato < ActiveRecord::Base

validates :nome, :email, presence: true, uniqueness: true 
validates :idade, :estado, :cargo, presence: true



def self.ransackable_attributes(*)
      %w( nome email idade estado cargo  ) + _ransackers.keys
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @search = Contato.search(params[:q])
    @results = @search.result()

    #@contatos = @q.result
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  def search
    index
    render :index
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :idade, :estado, :cargo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_form.html.erb
<%= form_for(@contato) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_area :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_area :estado %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_area :cargo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form' %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

app/views/contatos/index.html.erb
  <%= render partial: 'ransack_advanced_search/quick_search',
    locals: {
       search_url: advanced_search_contatos_path, # POST route we created above
       redirect_path: contatos_path # GET redirect path, to return after some actions
    }
  %>
<p id="notice"><%= notice %></p>

<h1>Listing Contatos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Idade</th>
      <th>Estado</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos = @results %>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.idade %></td>
        <td><%= contato.estado %></td>
        <td><%= contato.cargo %></td>
        <td><%= link_to 'Show', contato %></td>
        <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
        <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path %>

app/views/contatos/new.html.erb
<h1>New Contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contatos_path %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @contato.idade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @contato.estado %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @contato.cargo %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Segmentacao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <div class="hero-unit">
   <%= yield(:ransack_advanced_search_setup) %>
</div>
  <head>
<body>

<%= yield %>

</body>
</html>